name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image and publish
      run: | 
       VERSION=$(date +%s)
       docker build . --file Dockerfile --tag docker.pkg.github.com/aakashsgr/dockerfile/test:${VERSION}
       docker login docker.pkg.github.com --username aakashsgr --password ${{ secrets.GITHUB_TOKEN }}
       docker push docker.pkg.github.com/aakashsgr/dockerfile/test:${VERSION}
       docker run -t pythonaction/python_docker python Task1_Test.py
