name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2   
    - name: Build the Docker image and publish
      run: | 
       VERSION=$(date +%s)
       docker build . --file Dockerfile --tag docker.pkg.github.com/aakashsgr/dockerfile/test:${VERSION} 
       docker login docker.pkg.github.com --username aakashsgr --password ${{ secrets.GITHUB_TOKEN }}
       docker push docker.pkg.github.com/aakashsgr/dockerfile/test:${VERSION}
       docker images -a
       # docker pull docker.pkg.github.com/aakashsgr/dockerfile/test:1598032174
       docker run -t docker.pkg.github.com/aakashsgr/dockerfile/test:1598032174 
       docker ps -a
